---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:16-alpine
    when:
      event:
        - push
    commands:
      - yarn install --frozen-lockfile

  - name: lint
    image: node:16-alpine
    when:
      event:
        - push
    depends_on:
      - setup
    commands:
      - yarn lint

  - name: test
    image: node:16-alpine
    when:
      event:
        - push
    depends_on:
      - setup
    commands:
      - yarn coverage
    environment:
      MONGO_URL: mongodb://mongodb:27017/vote-test
      REDIS_URL: redis

  # - name: coverage
  #   image: node:16-alpine
  #   when:
  #     event:
  #       - push
  #   depends_on:
  #     - test
  #   commands:
  #     -
  #   environment:
  #     COVERALLS_REPO_TOKEN:
  #       from_secret: coveralls_token
  #     COVERALLS_SERVICE_NAME: drone
  #     COVERALLS_GIT_BRANCH: ${DRONE_BRANCH}
  #     COVERALLS_SERVICE_NUMBER: ${DRONE_BUILD_NUMBER}

  - name: build
    image: node:16-alpine
    when:
      event:
        - push
      branch:
        exclude: [prod]
    depends_on:
      - setup
    commands:
      - yarn build
      - yarn build:cli

  - name: server
    image: node:16-alpine
    detach: true
    when:
      event:
        - push
    depends_on:
      - build
    commands:
      - yarn start
    environment:
      NODE_ENV: test
      MONGO_URL: mongodb://mongodb:27017/vote-test
      REDIS_URL: redis
      HOST: 0.0.0.0

  - name: playwright
    image: mcr.microsoft.com/playwright:v1.30.0-focal
    when:
      event:
        - push
    depends_on:
      - build
    commands:
      - ./wait-for-it.sh server:3000 -t 30
      - yarn playwright test
    environment:
      BASE_URL: http://server:3000

  - name: docker
    image: plugins/docker
    when:
      branch:
        - prod
      event: push
      status: success
    depends_on:
      - lint
      - test
      - playwright
      - build
    settings:
      repo: abakus/vote
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - version-${DRONE_COMMIT_SHA:0:7}
        - latest
      build_args:
        - RELEASE=version-${DRONE_COMMIT_SHA:0:7}

  - name: Deploy
    image: abakus/ansible-deploy
    when:
      branch:
        - prod
      event: push
      status: success
    depends_on:
      - docker
    settings:
      playbook: /infrastructure/esas/playbooks/deploy.yml
      repository:
        from_secret: infra_repository
      tags:
        - vote
      limit: esas
      extra_vars: vote_version=version-${DRONE_COMMIT_SHA:0:7}
      inventory: /infrastructure/inventory
      vault_password:
        from_secret: ansible_vault_password
      private_key:
        from_secret: infra_deploy_key

services:
  - name: mongodb
    image: mongo:4.4

  - name: redis
    image: redis:6.0

---
kind: signature
hmac: de4f6c10d05a6d14bbd096067143a17bd6a545411b9f2582123e3192260861e1
