---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:14
    when:
      event:
        - push
        - pull_request
    commands:
      - yarn
    depends_on:
      - clone

  - name: lint
    image: node:14
    when:
      event:
        - push
        - pull_request
    depends_on:
      - setup
    commands:
      - yarn lint

  - name: test
    image: node:14
    when:
      event:
        - push
        - pull_request
    depends_on:
      - setup
    commands:
      - MONGO_URL=mongodb://mongodb:27017/vote-test REDIS_URL=redis yarn mocha

  - name: coverage
    image: node:14
    when:
      event:
        - pull_request
    depends_on:
      - test
    commands:
      - yarn coverage
    environment:
      COVERALLS_REPO_TOKEN:
        from_secret: coveralls_token
      COVERALLS_SERVICE_NAME: drone
      COVERALLS_GIT_BRANCH: ${DRONE_BRANCH}
      COVERALLS_SERVICE_NUMBER: ${DRONE_BUILD_NUMBER}

  - name: build
    image: node:14
    when:
      event:
        - push
        - pull_request
      branch:
        exclude: [prod]
    depends_on:
      - setup
    commands:
      - yarn build

  - name: protractor
    image: circleci/node:14-browsers
    # We run as root, because the docker daemon
    # no-new-priviliges flag
    # prohibits us from running sudo
    user: root
    when:
      event:
        - push
        - pull_request
    depends_on:
      - setup
    commands:
      # This image runs with a custom user (circleci)by default,
      # and chrome headless doesn't work for the root user.
      # --> Fix some file permissions before start
      - mkdir -p /root/.config/yarn/
      - chown -R circleci:circleci .
      - chown -R circleci:circleci /root/
      - su circleci
      - MONGO_URL=mongodb://mongodb:27017/vote-integration-test REDIS_URL=redis HEADLESS=true yarn protractor

  - name: docker
    image: plugins/docker
    when:
      branch:
        - build
      event: push
      status: success
    depends_on:
      - lint
      - test
      - protractor
      - build
    settings:
      repo: abakus/vote
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - version-${DRONE_COMMIT_SHA:0:7}
        - latest
      build_args:
        - RELEASE=version-${DRONE_COMMIT_SHA:0:7}

services:
  - name: mongodb
    image: mongo:4.4

  - name: redis
    image: redis:6.0

---
kind: signature
hmac: 7b739c5ad6e81bd59b8b64fa5484095cc4dec4b030acd7a62263abd6f8b63b25
