version: '2'

services:
  mongo:
    image: mongo:4.4
  redis:
    image: redis:6.0
  vote:
    image: abakus/vote:latest
    environment:
      # Reed more about these in the README-file in the base directory
      MONGO_URL: 'mongodb://mongo:27017/vote'
      REDIS_URL: 'redis'
      COOKIE_SECRET: 'long-secret-here-is-important'
      LOGO_SRC: 'https://raw.githubusercontent.com/webkom/lego/master/assets/abakus_webkom.png'
      ICON_SRC: 'https://raw.githubusercontent.com/webkom/lego/master/assets/abakus_webkom.png'
      FROM: 'YourCompany'
      FROM_MAIL: "noreply@example.com"
      SMTP_URL: 'smtps://username:password@smtp.example.com'
      FRONTEND_URL: 'https://vote.example.com'
    ports:
      - '127.0.0.1:3000:3000'
